package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 02 09:26:21 PDT 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void execureEmpQuery(String empid);
}
